<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>single_fr3_description</name>
  <version>0.1.0</version>
  <description>Single-arm FR3 robot description wrapper for ROS 2 Jazzy.</description>
  <maintainer email="maintainer@example.com">single_fr3_rviz maintainers</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>franka_description</depend>
  <depend>franka_hardware</depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

