joint_limits:
  fr3_joint1:
    has_velocity_limits: true
    max_velocity: 0.524
    has_acceleration_limits: true
    max_acceleration: 1.50
  fr3_joint2:
    has_velocity_limits: true
    max_velocity: 0.524
    has_acceleration_limits: true
    max_acceleration: 0.75
  fr3_joint3:
    has_velocity_limits: true
    max_velocity: 0.524
    has_acceleration_limits: true
    max_acceleration: 1.00
  fr3_joint4:
    has_velocity_limits: true
    max_velocity: 0.524
    has_acceleration_limits: true
    max_acceleration: 1.25
  fr3_joint5:
    has_velocity_limits: true
    max_velocity: 1.052
    has_acceleration_limits: true
    max_acceleration: 1.50
  fr3_joint6:
    has_velocity_limits: true
    max_velocity: 0.836
    has_acceleration_limits: true
    max_acceleration: 2.00
  fr3_joint7:
    has_velocity_limits: true
    max_velocity: 1.052
    has_acceleration_limits: true
    max_acceleration: 2.00

