planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05

fr3_arm:
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
  projection_evaluator: joints(fr3_joint1,fr3_joint2)
  longest_valid_segment_fraction: 0.005

